TARGETS = island-fpga.sch

# Dummy targets to remake dependencies
island-fpga.tgt: \
	island-fpga-north.tgt \
	island-fpga-south.tgt \
	island-fpga-east.tgt \
	island-fpga-west.tgt \
	island-fpga-power.tgt \

include ../Makefile.common
