TARGETS = island-fpga.sch

island-fpga.renum.sch: \
	island-fpga-north.renum.sch \
	island-fpga-south.renum.sch \
	island-fpga-east.renum.sch \
	island-fpga-west.renum.sch \

include ../Makefile.common
