BOARD = island-west
REV = Ab4
TARGETS = $(BOARD).sch

SCHEM_FILES = \
	island-west-lvds.sch \
	island-west-clock.sch \

LAYER_COLORS = \
	--layer-color-1 "\#8b2323" \
	--layer-color-2 "\#3a5fcd" \
	--layer-color-3 "\#404040" \
	--layer-color-4 "\#ff0000" \
	--layer-color-5 "\#0000ff" \
	--layer-color-6 "\#408040" \

# This is a high-speed board with only plated through-holes.
IS_FRONT_ONLY = 1
IS_HS = 1

include ../Makefile.common
