BOARD = face-in
REV = 0
TARGETS = $(BOARD).sch

# Dummy targets to remake dependencies
SCHEM_FILES = \

LAYER_COLORS = \
	--layer-color-1 "\#8b2323" \
	--layer-color-2 "\#3a5fcd" \
	--layer-color-3 "\#404040" \
	--layer-color-4 "\#ff0000" \
	--layer-color-5 "\#408040" \

# This is a high-speed board without only plated holes
IS_FRONT_ONLY = 1
IS_HS = 1

include ../Makefile.common
